language: generic
dist: bionic
services:
  - docker
env:
  global:
    - zola_version="0.11.0"
    - vcs_ref="$TRAVIS_COMMIT"
    - tag_image="thibaultmorin/zola"
    - tag_version="$zola_version-$TRAVIS_CPU_ARCH"
    - tag="$tag_image:$tag_version"
before_install: ./scripts/before_install.sh
script: ./scripts/build.sh
after_success:
  - ./scripts/manifest.sh
  - curl --data "" https://hooks.microbadger.com/images/thibaultmorin/zola/1fOBVfKip6cv8KXonRU77Cdpdf4=
